---
- hosts: "{{ group }}"
  tasks:
    - service: name=firewalld enabled=yes
    - service: name=firewalld state=started

    # DEV
#   - firewalld: permanent=yes zone=trusted source='10.18.122.22/32' state=enabled
    # Public Service
    - firewalld: permanent=yes zone=public service=http state=enabled
    - firewalld: permanent=yes zone=public service=https state=enabled
#   - firewalld: permanent=yes zone=public port=8000-10000/tcp state=enabled immediate=yes
    # Pantheon
    # firewalld: permanent=yes zone=public port=12345/tcp state=enabled immediate=yes
    # Etcd
    # firewalld: permanent=yes zone=public port=2379-2380/tcp state=enabled immediate=yes
    # GlusterFS
    - firewalld: permanent=yes zone=public port=8472/udp state=enabled immediate=yes
    # Cluster
    - firewalld: permanent=yes zone=trusted source='172.17.0.0/16' state=enabled immediate=yes
  become: yes
  gather_facts: no
