---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  tasks:
    - name: 根据模板生成skydns-deploy配置
      template:
        src: "../templates/dns/skydns-deploy.yaml.j2"
        dest: "/home/wuzhongyang/kubectl/skydns-deploy.yaml"
    # - name: 根据模板生成skydns-rc配置
    #   template:
    #     src: "../templates/dns/skydns-rc.yaml.j2"
    #     dest: "/tmp/skydns-rc.yaml"
    # - name: 根据模板生成skydns-svc配置
    #   template:
    #     src: "../templates/dns/skydns-svc.yaml.j2"
    #     dest: "/tmp/skydns-svc.yaml"
  become: search
  gather_facts: yes
