version: 0.1
log:
  level: debug
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
        # layerinfo: inmemory
    # 本地文件存储
    # filesystem:
    #     rootdirectory: /storage
    maintenance:
        uploadpurging:
            enabled: false
    delete:
        enabled: true
http:
    addr: :5000
    headers:
      X-Content-Type-Options: [nosniff]
auth:
  token:
    issuer: registry-token-issuer
    realm: http://proxy/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service

# 由环境变量控制
# notifications:
#   endpoints:
#     - name: harbor
#       disabled: false
#       url: http://ui/service/notifications
#       timeout: 3000ms
#       threshold: 5
#       backoff: 1s
