---
- hosts: "{{ dc }}"
  tasks:
    - name: 安装系统工具
      yum: name=ack,htop,sysstat,mlocate,bash-completion,vim state=latest

    - name: 调整服务器配置
      command: tuned-adm profile latency-performance
  sudo: yes
  gather_facts: no
