---
# 安装服务
- name: 创建kapacitor根目录
- file: 
    path: "{{ kapacitor_home }}"
    state: directory 
    owner: "{{ kapacitor_user }}" 
    group: "{{ kapacitor_group }}" 
    mode: 0755

- name: 创建kapacitor数据目录
  file: 
    path: "{{ kapacitor_data }}"
    state: directory 
    owner: "{{ kapacitor_user }}" 
    group: "{{ kapacitor_group }}" 
    mode: 0755

- name: 创建kapacitor版本目录
  file: 
    path: "{{ kapacitor_home }}/{{ kapacitor_release }}"
    state: directory 
    owner: "{{ kapacitor_user }}" 
    group: "{{ kapacitor_group }}" 
    mode: 0755

- name: 解压缩kapacitor压缩包
  unarchive:
    src: "releases/{{ kapacitor_release }}_linux_amd64.tar.gz"
    dest: "{{ kapacitor_home }}"

- name: 设置目录权限
  file:
    path: "{{ kapacitor_home }}/{{ kapacitor_release }}"
    owner: "{{ kapacitor_user }}" 
    group: "{{ kapacitor_group }}" 
    recurse: yes

- name: 创建目录软链 
  file:
    path: "{{ kapacitor_home }}/kapacitor"
    src: "{{ kapacitor_home }}/{{ kapacitor_release }}"
    owner: "{{ kapacitor_user }}" 
    group: "{{ kapacitor_group }}" 
    state: link

- name: 创建kapacitor系统服务
  template:
    src: "kapacitor.service.j2"
    dest: "/etc/systemd/system/{{ kapacitor_systemd['name'] }}.service"

- name: 重启系统服务
  command: systemctl daemon-reload

