---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  tasks:
    - name: 清除yum中的nodejs
      become: yes
      become_user: root 
      become_method: sudo
      yum:
        name: nodejs
        state: absent
    - name: 下载nodejs的压缩包
      get_url: 
        url: https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-x64.tar.xz 
        dest: "{{ home_src_dir }}"
    - name: 解压缩nodejs的压缩包 
      unarchive: 
        src: "{{ home_src_dir }}/node-v8.11.3-linux-x64.tar.xz"
        dest: "{{ home_src_dir }}"
        remote_src: true
    - name: 删除yum的压缩包
      file:
        path: "{{ home_src_dir }}/node-v8.11.3-linux-x64.tar.xz"
        state: absent
    - name: 配置国内镜像(使用代理就不需要配置了)
      shell: /bin/zsh -l -c "source {{ home_dir }}/.zshrc && npm config set registry https://registry.npm.taobao.org"
    - name: 安装typescript
      shell: /bin/zsh -l -c "source {{ home_dir }}/.zshrc && npm install -g typescript"
    - name: 安装angular
      shell: /bin/zsh -l -c "source {{ home_dir }}/.zshrc && npm install -g @angular/cli"
    # - name: 安装NgAlain
    #   command: npm install -g @angular-devkit/core @angular-devkit/schematics @schematics/schematics rxjs
