---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  tasks:
    - name: 清除yum中的nodejs
      yum:
        name: nodejs
        state: absent
      tags: nodejs 
    - name: 清除源码相关的nodejs-lib
      file:
        path: "/usr/local/lib/node_modules"
        state: absent
      tags: nodejs 
    - name: 清除源码相关的nodejs-include
      file:
        path: "/usr/local/include/node"
        state: absent
      tags: nodejs 
    - name: 清除源码相关的nodejs-bin
      file:
        path: "/usr/local/bin/node"
        state: absent
      tags: nodejs 
    - name: 清除源码相关的npm
      file:
        path: "/usr/local/bin/npm"
        state: absent
      tags: nodejs 
    - name: 下载nodejs的压缩包
      get_url: 
        url: https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-x64.tar.xz 
        dest: "{{ home_src_dir }}"
      tags: nodejs 
    - name: 解压缩nodejs的压缩包 
      unarchive: 
        src: "{{ home_src_dir }}/node-v8.11.3-linux-x64.tar.xz"
        dest: "{{ home_src_dir }}"
        remote_src: true
      tags: nodejs 
    - name: 删除yum的压缩包 
      file:
        path: "{{ home_src_dir }}/node-v8.11.3-linux-x64.tar.xz"
        state: absent
      tags: nodejs 
    - name: 复制node文件 
      file: 
        src: "{{ home_src_dir }}/node-v8.11.3-linux-x64/bin/node" 
        dest: "/usr/local/bin/node" 
        state: link 
      tags: nodejs 
    - name: 复制npm文件 
      file: 
        src: "{{ home_src_dir }}/node-v8.11.3-linux-x64/bin/npm" 
        dest: "/usr/local/bin/npm" 
        state: link 
      tags: nodejs 
    - name: 配置国内镜像
      command: npm config set registry https://registry.npm.taobao.org 
      tags: npm 
    - name: 安装typescript 
      command: npm install -g typescript
      tags: npm 
    - name: 安装angular
      command: npm install -g @angular/cli
      tags: npm 
    # - name: 安装NgAlain
    #   command: npm install -g @angular-devkit/core @angular-devkit/schematics @schematics/schematics rxjs
    # 编译版本的太慢了
    # - name: 下载nodejs的压缩包
    #   get_url: 
    #     url: http://nodejs.org/dist/v8.11.3/node-v8.11.3.tar.gz
    #     dest: "{{ home_src_dir }}"
    #   tags: nodejs 
    # - name: 解压缩nodejs的压缩包 
    #   unarchive: 
    #     src: "{{ home_src_dir }}/node-v8.11.3.tar.gz"
    #     dest: "{{ home_src_dir }}"
    #     remote_src: true
    #   tags: nodejs 
    # - name: 删除yum的压缩包 
    #   file:
      # command: npm config set registry http://registry.cnpmjs.org
    #     path: "{{ home_src_dir }}/node-v8.11.3.tar.gz"
    #     state: absent
    #   tags: nodejs 
    # - name: 配置nodejs相关文件
    #   command: ./configure
    #   args:
    #     chdir: "{{ home_src_dir }}/node-v8.11.3"
    # - name: 编译nodejs
    #   command: make 
    #   args:
    #     chdir: "{{ home_src_dir }}/node-v8.11.3"
    # - name: 编译nodejs
    #   command: make install
    #   args:
    #     chdir: "{{ home_src_dir }}/node-v8.11.3"
  become: yes
  gather_facts: no
