---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  tasks:
    - name: 安装相关组件
      yum:
        name: yum-utils,device-mapper-persistent-data,lvm2 
        state: latest
    - name: 安装阿里docker源
      shell: "yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo" 
      args:
        executable: /bin/zsh
    - name: 替换docker源配置 
      shell: "sed -i 's+download-stage.docker.com+mirrors.tuna.tsinghua.edu.cn/docker-ce+' /etc/yum.repos.d/docker-ce.repo" 
      args:
        executable: /bin/zsh
    - name: 安装docker-ce
      yum: 
        name: docker-ce
        state: latest
    - name: 复制docker系统服务
      copy: 
        src: ../files/system/docker.service.d 
        dest: /etc/systemd/system/
    - name: 检查linux系统配置文件中，网桥arptables的设定 
      lineinfile:
        dest: /etc/sysctl.d/99-sysctl.conf
        state: present
        line: "net.bridge.bridge-nf-call-arptables = 1"
    - name: 检查linux系统配置文件中，网桥ip6tables的设定 
      lineinfile:
        dest: /etc/sysctl.d/99-sysctl.conf
        state: present
        line: "net.bridge.bridge-nf-call-ip6tables = 1"
    - name: 检查linux系统配置文件中，网桥iptables的设定 
      lineinfile:
        dest: /etc/sysctl.d/99-sysctl.conf
        state: present
        line: "net.bridge.bridge-nf-call-iptables = 1"
    - name: 重启系统服务
      command: systemctl daemon-reload
    - name: 启用docker
      service: 
        name: docker 
        enabled: yes
    - name: 启动docker
      service: 
        name: docker 
        state: started
    - name: 下载docker-compose
      shell: "curl -L https://get.daocloud.io/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` > /usr/bin/docker-compose" 
      args:
        executable: /bin/zsh
    - name: 更新docker-compose命令权限
      file: 
        path: /usr/bin/docker-compose 
        mode: 0755
    - name: 确保 "docker" group存在
      group:
        name: docker 
        state: present
    - name: 添加用户至group组
      command: gpasswd -a {{ owner }} docker
    - name: 初始化network 
      command: docker network create {{ owner }}
    - name: 添加daocloud加速器 
      shell: "curl -sSL https://get.daocloud.io/daotools/set_mirror.sh | sh -s http://1401b515.m.daocloud.io" 
      args:
        executable: /bin/zsh
    - name: 重启docker
      service: 
        name: docker 
        state: restarted
  become: yes
  gather_facts: no
