---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  tasks:
    - name: 从github获取fzf
      git:
        repo: "https://github.com/junegunn/fzf.git" 
        dest: "{{ home_dir }}/.fzf" 
        clone: yes 
        update: yes
      tags: github
    - name: 安装fzf 
      command: "{{ home_dir }}/.fzf/install --all" 
      tags: fzf 
    - name: 删除初始的key-bindings.zsh文件
      file:
        path: "{{ home_dir }}/.fzf/shell/key-bindings.zsh"
        state: absent 
      tags: fzf 
    - name: 新增key-bindings.zsh的软链
      file:
        src: "{{ home_tool_dir }}/key-bindings.zsh"
        dest: "{{ home_dir }}/.fzf/shell/key-bindings.zsh"
        owner: "{{ owner }}"
        group: "{{ owner_group }}" 
        state: link 
      tags: fzf 
