---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  remote_user: wuzhongyang
  tasks:
    - name: 下载go的压缩包
      get_url: 
        # url: https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz
        url: https://mirrors.nju.edu.cn/golang/go1.8.linux-amd64.tar.gz
        dest: "{{ home_dir }}"
      tags: download
    - name: 解压缩go的压缩包 
      unarchive: 
        src: "{{ home_dir }}/go1.8.linux-amd64.tar.gz"
        dest: "{{ home_dir }}"
        remote_src: true
      tags: file
    - name: 删除go的压缩包 
      file:
        path: "{{ home_dir }}/go1.8.linux-amd64.tar.gz"
        state: absent
      tags : file
    - name:  创建go项目的文件夹 
      file:
        path: "{{ home_dir }}/go_project/src"
        state: directory
      tags: file 
    - name: 安装glide依赖管理工具
      become: yes
      become_user: root 
      become_method: sudo
      yum:
        name: glide 
        state: latest 
      tags: install 
    - name: 检查gopkg目录是否存在 
      file:
        path: "{{ home_vim_dir }}/go/gopkg"
        state: directory
      tags: vimgo 
