---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  remote_user: wuzhongyang
    - name: 关闭防火墙 
      service: 
        name: firewalld 
        state: stopped 
    - name: 下线防火墙 
      service: 
        name: firewalld 
        enabled: no 
    - name: 关闭swap内存 
      command: swapoff -a 
    - name: 注释swap自动挂载 
      lineinfile:
        dest: /etc/fstab
        state: absent 
        line: "/dev/mapper/centos-swap swap                    swap    defaults        0 0"
    - name: 去除selinux
      lineinfile:
        dest: /etc/sysconfig/selinux
        state: absent 
        line: "SELINUX=enforcing"
    - name: 关闭selinux
      lineinfile:
        dest: /etc/sysconfig/selinux
        state: present 
        line: "SELINUX=disabled"
    - name: 调整k8s内核参数 
      lineinfile:
        dest: /etc/sysctl.d/k8s.conf
        state: present 
        line: "net.bridge.bridge-nf-call-ip6tables = 1 \n net.bridge.bridge-nf-call-iptables = 1"
    - name: 修改sshd 
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present 
        line: "ClientAliveInterval 10"
    - name: 修改sshd 
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present 
        line: "TCPKeepAlive yes"
    - name: 重启sshd 
      service: 
        name: firewalld 
        state: restart 

    - name: 复制k8s的repo 
      copy: 
        src: ../files/system/kubernetes.repo 
        dest: /etc/yum.repos.d/
    - name: 安装相关组件(yum需要翻墙)
      yum:
        name: kubeadm,kubelet,kubectl 
        state: latest
    - name: 启用kubelet
      service: 
        name: kubelet 
        enabled: yes
    - name: 启动kubelet
      service: 
        name: kubelet 
        state: started
    - name: 部署k8s
      command: "kubeadm init --kubernetes-version=v1.9.2 --pod-network-cidr=10.244.0.0/16" 
    - name: 处理kubectl
      command: "mkdir -p $HOME/.kube"
    - name: 处理kubectl
      command: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
    - name: 处理kubectl
      command: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"
    - name: 安装network addon
      command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml"
    - name: 允许master节点调度
      command: "kubectl taint nodes --all node-role.kubernetes.io/master-"
