---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  tasks:
    - name: 下载七牛云的qshell
      git:
        repo: "https://git.oschina.net/zhangchao123/qshell.git" 
        dest: "{{ home_dir }}/src/qshell" 
        clone: yes 
        update: yes
      tags: qshell
    - name: 复制qshell
      copy: 
        src: "{{ home_dir }}/src/qshell/qshell/qshell_linux_amd64" 
        dest: /usr/bin/qshell
        remote_src: yes
      become: yes
      become_user: root
      become_method: sudo
      tags: qshell
    - name: 更新私钥文件权限
      file: 
        path: "{{ item.path }}" 
        mode: "644"
      become: yes
      become_user: root
      become_method: sudo
      tags: qshell
    - name: 添加qshell的account 
      command: qshell account 9HdHsPGJ7lxHMCtzB0q8qFatx-c5QpvigPy0Uog- 8N0hA_ngYi0vGxDkBm4yagZs3SFTUiTOY3fnUCIG 
      tags: qshell
