---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  tasks:
    - name: 安装系统工具
      yum: 
        name: ack,htop,iotop,iftop,sysstat,mlocate,bash-completion,vim 
        state: latest
    - name: 安装相关插件
      yum:
        name: m2crypto,epel-release,gcc,python34,python34-devel,python34-setuptools,ncurses-devel,wget,libzip,bzip2,git,unzip,cscope,gitflow,cmake,gcc-c++,mariadb,ctags,libevent-devel,zsh
        state: latest
    - name: 调整服务器配置
      command: tuned-adm profile virtual-guest
    - name: 避免升级内核
      lineinfile: 
        dest: /etc/yum.conf 
        state: present
        line: "exclude=kernel* centos-release* redhat-release*"
    - name: 开启时间同步
      yum: 
        name: ntp 
        state: latest
    - name: 启用时间同步服务
      service: 
        name: ntpd 
        enabled: yes
    - name: 启动时间同步服务
      service: 
        name: ntpd 
        state: started 
    - name: 复制login banner文件
      copy: 
        src: ../files/banners
        dest: /etc/ssh/sshd-banner
      tags: banner
    - name: 增加banner文件配置 
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#Banner none'
        line: "Banner /etc/ssh/sshd-banner"
      tags: banner
    - name: 重启sshd服务    
      service: 
        name: sshd 
        state: restarted 
      tags: banner
    - name: 从github获取personal_conf 
      git:
        repo: "{{ tool_git_href }}" 
        dest: "{{ home_tool_dir }}" 
        key_file: "{{ home_dir }}/.ssh/id_rsa"
        accept_hostkey: yes
        clone: yes 
        update: yes
      become_user: "{{ owner }}"
      tags: github
    - name: 复制.gitconfig文件 
      file: 
        src: "{{ home_tool_dir }}/.gitconfig" 
        dest: "{{ home_dir }}/.gitconfig" 
        owner: "{{ owner }}"
        group: "{{ owner_group }}" 
        state: link 
    - name: 复制locale文件 
      copy: 
        src: "{{ home_tool_dir }}/locale.conf"
        dest: "/etc" 
    - name: 删除原版.bash_profile文件 
      file:
        path: "{{ home_dir }}/.bash_profile"
        state: absent
    - name: 复制.bash_profile文件 
      file: 
        src: "{{ home_tool_dir }}/.bash_profile" 
        dest: "{{ home_dir }}/.bash_profile" 
        owner: "{{ owner }}"
        group: "{{ owner_group }}" 
        state: link
    - name: 安装pip3
      command: easy_install-3.4 pip 
  become: yes
  gather_facts: no
