---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  remote_user: wuzhongyang
  tasks:
    - name: 安装tmux 
      become: yes
      become_user: root
      become_method: sudo
      yum:
        name: tmux 
        state: latest 
      tags: install 
    - name: 从github获取personal_conf 
      git:
        repo: "{{ tool_git_href }}" 
        dest: "{{ home_tool_dir }}" 
        clone: no 
        update: yes
      tags: github
    - name: 删除初始化的tmux配置文件 
      file:
        path: "{{ home_dir }}/.tmux.conf"
        state: absent 
      tags: file 
    - name: 创建个人tmux的配置文件软链
      file:
        src: "{{ home_tool_dir }}/.tmux.conf"
        dest: "{{ home_dir }}/.tmux.conf"
        owner: "{{ owner }}"
        group: "{{ owner_group }}" 
        state: link 
      tags: file

