---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  remote_user: wuzhongyang
  tasks:
    - name: 安装YCM 
      shell: source {{ home_dir }}/.bash_profile && python3 {{ home_dir }}/.vim/bundle/YouCompleteMe/install.py --gocode-completer --tern-completer 
      args:
        executable: /bin/bash
