---
- hosts: corp
  vars_files:
    # - ../inventory/vars/"{{ group }}"
    - ../inventory/vars/develop
  remote_user: wuzhongyang
  tasks:
    - name: download go binary
      get_url: 
        url: https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz
        dest: "{{ home_dir }}"
      tags: download
    - name: tar -zxvf go binary 
      unarchive: 
        src: "{{ home_dir }}/go1.8.linux-amd64.tar.gz"
        dest: "{{ home_dir }}"
        remote_src: true
      tags: file
    - name: tar -zxvf go binary 
      file:
        path: "{{ home_dir }}/go1.8.linux-amd64.tar.gz"
        state: absent
      tags : file
    - name: install vim go plugin
      # 需要zsh的支持
      shell: /bin/zsh -l -c "vim +GoInstallBinaries +qall"
      args:
        chdir: "{{ home_dir }}"
      ignore_errors: yes
      tags: plugin 
    - name: make go_project dir 
      file:
        path: "{{ home_dir }}/go_project/src"
        state: directory
      tags: file 

