---
- hosts: corp
  vars_files:
    # - ../inventory/vars/"{{ group }}"
    - ../inventory/vars/develop
  remote_user: wuzhongyang
  tasks:
    - name: check and install zsh 
      become: yes
      become_user: root 
      become_method: sudo
      yum:
        name: zsh
        state: present
      tags: install 
    - name: get personal_conf from github
      git:
        repo: "{{ tool_git_href }}" 
        dest: "{{ home_tool_dir }}" 
        clone: no 
        update: yes
      tags: github
    - name: check Zsh exists
      yum:
        name: zsh
        state: present
      tags: file 
    - name: download oh-my-zsh
      shell: sh "{{ home_tool_dir }}/oh-my-zsh-install.sh" 
      tags: file 
    - name: remove init .zshrc file 
      file:
        path: "{{ home_dir }}/.zshrc"
        state: absent 
      tags: file 
    - name: add .zshrc link 
      file:
        src: "{{ home_tool_dir }}/.zshrc"
        dest: "{{ home_dir }}/.zshrc"
        owner: "{{ owner }}"
        group: "{{ group }}" 
        state: link 
      tags: file 
    - name: set shell is zsh
      # 需要提交密码
      shell: "chsh -s /bin/zsh <<< {{chsh_password}}"
      tags: file 
    - name: install autojump
      shell: "{{ home_tool_dir }}/autojump/install.py"
      args:
        chdir: "{{ home_tool_dir }}/autojump"
        executable: /bin/zsh
      tags: install

