---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  tasks:
    - name: 复制docker的repo 
      copy: 
        src: ../files/Docker.repo 
        dest: /etc/yum.repos.d/
    - name: 安装docker-engine
      yum: 
        name: docker-engine 
        state: latest

    - name: 复制docker系统服务
      copy: 
        src: ../files/system/docker.service.d 
        dest: /etc/systemd/system/

    - name: 检查linux系统配置文件中，网桥arptables的设定 
      lineinfile:
        dest: /etc/sysctl.d/99-sysctl.conf
        state: present
        line: "net.bridge.bridge-nf-call-arptables = 1"
    - name: 检查linux系统配置文件中，网桥ip6tables的设定 
      lineinfile:
        dest: /etc/sysctl.d/99-sysctl.conf
        state: present
        line: "net.bridge.bridge-nf-call-ip6tables = 1"
    - name: 检查linux系统配置文件中，网桥iptables的设定 
      lineinfile:
        dest: /etc/sysctl.d/99-sysctl.conf
        state: present
        line: "net.bridge.bridge-nf-call-iptables = 1"

    - name: 重启系统服务
      command: systemctl daemon-reload
    - name: 启用docker
      service: 
        name: docker 
        enabled: yes
    - name: 启动docker
      service: 
        name: docker 
        state: started

    - name: 初始化docker目录
      file: 
        path: "/root/.docker" 
        state: directory
    - name: 根据模板生成docker配置
      template: 
        src: ../templates/docker_config.j2 
        dest: /root/.docker/config.json
    - name: 拉取rhel7的镜像
      command: "docker pull {{ docker_registry }}/rhel7/pod-infrastructure"
    - name: 拉取hyperkube镜像 
      command: "docker pull {{ docker_registry }}/google_containers/hyperkube:v1.3.0"

    # 安装docker-compose
    - name: 复制docker-compose的执行工具(下载地址被墙，可去github查询) 
      copy: 
        src: ../releases/docker-compose-Linux-x86_64 
        dest: /usr/bin/docker-compose
    - name: 更新docker-compose命令权限
      file: 
        path: /usr/bin/docker-compose 
        mode: 0755

  become: yes
  gather_facts: no
