---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
    # - ../inventory/vars/telegraf.vault
  roles:
    - telegraf
  tasks:
    - name: 根据模板生成telegraf.service配置 
      template:
        src: "../templates/telegraf.service.j2"
        dest: "/etc/systemd/system/telegraf.service"
      tags: configuration
    - name: 根据模板生成telegraf.service配置 
      template:
        src: "../templates/telegraf.conf.j2"
        dest: "{{ telegraf_config }}"
        owner: "{{ telegraf_user }}" 
        group: "{{ telegraf_group }}"
      tags: configuration
    - name: 重启系统服务
      command: systemctl daemon-reload
    - name: 重启telegraf
      service: name=telegraf state=restarted enabled=yes
  become: yes
  gather_facts: yes
