---
- name: 创建data目录 
  file: 
    state: directory 
    path: "{{ es_data_dir }}" 
    owner: "{{ es_user }}" 
    group: "{{ es_group }}"

- name: 创建log目录 
  file: 
    state: directory 
    path: "{{ es_log_dir }}" 
    owner: "{{ es_user }}" 
    group: "{{ es_group }}"

- name: 创建config目录 
  file: 
    state: directory 
    path: "{{ es_conf_dir }}" 
    owner: "{{ es_user }}" 
    group: "{{ es_group }}"

- name: 根据模板生成配置文件 
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_conf_dir }}/elasticsearch.yml"
    owner: "{{ es_user }}" 
    group: "{{ es_group }}" 
    mode: 0644 
    force: yes
  tags:
    - configuration

- name: 复制日志配置 
  template:
    src: logging.yml.j2
    dest: "{{ es_conf_dir }}/logging.yml"
    owner: "{{ es_user }}" 
    group: "{{ es_group }}" 
    mode: 0644 
    force: yes
  tags:
    - configuration
