---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  remote_user: wuzhongyang
  tasks:
    - name: 复制k8s的admin.conf
      fetch:
        src: "{{ home_dir }}/.kube/config"
        dest: "{{ home_dir }}/.kube/config"
        flat: yes
