---
- hosts: "{{ group }}"
  vars_files:
    - ../inventory/vars/{{ group }}
  tasks:
    - name: 复制k8s的repo(国内aliyun源)
      copy: 
        src: ../files/system/kubernetes.repo 
        dest: /etc/yum.repos.d/
    - name: 安装相关组件
      yum:
        name: kubeadm,kubelet,kubectl,ipvsadm
        state: latest
    - name: 复制k8s.conf文件 
      copy: 
        src: "../files/k8s.conf" 
        dest: "/etc/sysctl.d/k8s.conf" 
    - name: 使k8s.conf修改生效 
      shell: sysctl -p /etc/sysctl.d/k8s.conf 
      args:
        executable: /bin/bash
    # - name: 启用ipvs模块（重启需再次加载）
    #   shell: modprobe ip_vs && modprobe ip_vs_rr && modprobe ip_vs_wrr && modprobe ip_vs_sh && modprobe nf_conntrack_ipv4 
    #   args:
    #     executable: /bin/bash
    - name: 创建.kube 
      file:
        path: "{{ home_dir }}/.kube"
        state: directory 
    - name: 复制k8s.admin.conf文件 
      copy: 
        src: "{{ home_dir }}/.kube/config" 
        dest: "{{ home_dir }}/.kube/config" 
    - name: 更改admin-conf的权限 
      file:
        path: "{{ home_dir }}/.kube/config"
        owner: "{{ owner }}"
        group: "{{ owner_group }}" 
        mode: 0644
    - name: 从国内源拉取kube镜像
      shell: docker pull {{ google_prefix }}.kube-proxy-amd64:v{{ kube_version }} &&
        docker pull {{ google_prefix }}.pause:{{ pause_version }} &&
        docker pull {{ google_prefix }}.etcd-amd64:{{ etcd_version }} &&
        docker pull {{ google_prefix }}.coredns:{{ coredns_version }} 
      args:
        executable: /bin/bash
    - name: 给kube镜像重新打标签
      shell: docker tag {{ google_prefix }}.kube-proxy-amd64:v{{ kube_version }} {{ kube_prefix }}/kube-proxy-amd64:v{{ kube_version }} &&
        docker tag {{ google_prefix }}.pause:{{ pause_version }} {{ kube_prefix }}/pause:{{ pause_version }} &&
        docker tag {{ google_prefix }}.etcd-amd64:{{ etcd_version }} {{ kube_prefix }}/etcd-amd64:{{ etcd_version }} &&
        docker tag {{ google_prefix }}.coredns:{{ coredns_version }} {{ kube_prefix }}/coredns:{{ coredns_version }}
      args:
        executable: /bin/bash
    - name: 删除kube镜像原先国内标签 
      shell: docker rmi {{ google_prefix }}.kube-proxy-amd64:v{{ kube_version }} &&
        docker rmi {{ google_prefix }}.pause:{{ pause_version }} &&
        docker rmi {{ google_prefix }}.etcd-amd64:{{ etcd_version }} &&
        docker rmi {{ google_prefix }}.coredns:{{ coredns_version }} 
      args:
        executable: /bin/bash
    - name: 加入集群
      shell: kubeadm join {{ master_ip }}:6443 --token {{ master_token }} --discovery-token-ca-cert-hash {{ master_token_ca }} 
      args:
        executable: /bin/bash
    - name: 安装network
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
      args:
        executable: /bin/bash
  become: yes
  gather_facts: no
