---

- name: 创建telegraf目录 
  file: 
    state: directory 
    path: "{{ telegraf_home }}" 
    owner: "{{ telegraf_user }}" 
    group: "{{ telegraf_group }}" 
    recurse: yes

- name: 复制telegraf的bin文件
  copy:
    src: "releases/{{ telegraf_bin }}"
    dest: "{{ telegraf_home }}/{{ telegraf_bin }}"
    owner: "{{ telegraf_user }}" 
    group: "{{ telegraf_group }}" 
    mode: 0755

- name: 创建telegraf的软链
  file:
    path: "{{ telegraf_home }}/telegraf"
    src: "{{ telegraf_home }}/{{ telegraf_bin }}"
    owner: "{{ telegraf_user }}" 
    group: "{{ telegraf_group }}" 
    state: link

- name: 配置telegraf的启动命令 
  template:
    src: telegraf.sh.j2
    dest: "{{ telegraf_home }}/telegraf.sh"
    owner: "{{ telegraf_user }}" 
    group: "{{ telegraf_group }}" 
    mode: 0755


